services:
  - type: web
    name: aqi-forecasting-system
    env: python
    buildCommand: pip install -r requirements.txt && python build.py
    startCommand: gunicorn app:application
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
